# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter: postgresql
  database: d38ppogcg52vl6 
  username: qcojusjuzqkzuo
  password: nQUzl-dhGSV3a2z2ceDc-gSxqC
  pool: 5
  timeout: 5000
