s3:
  bucket: "traveladdict-test"
  access_key_id: "AKIAIBIK5QDPRB6A322Q"
  secret_access_key: "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"
flickr:
  key: "951c0814caade8b4fc2b381778269126"
  secret: "9f84c972d99de24d"
google_maps:
  key: "AIzaSyCY7Iz4DN0iYHwMgJCRp7pJQzIy3iG89Eo"